### ISSUE TITLE
PUBG Cog: Problem building the embed

### ISSUE THREAD

**Issue by neoblizz** [UltimatePancake/Pancake-Cogs#11]
Any recommended fix?
```
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/muhammad/bots/skulls/cogs/pubg.py", line 142, in _distance
    await self.bot.say(embed=await self._build_embed(pubg_nickname, 'Distance', mode, region))
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message
```

**Comment by neoblizz** [comment]
Nevermind, it was that the information didn't exist for solo for that account.
